Adicionando Dicionário de Dados para uma Parte do Diagrama
SBD1/2023.2_Fear_and_Hunger pull request #2
Opened 2023-09-25 14:58 UTC by zzzBECK

**Descrição:**

Este Pull Request adiciona o dicionário de dados para uma parte específica do nosso diagrama de banco de dados. O dicionário de dados é uma parte crucial da documentação do nosso projeto, pois fornece informações detalhadas sobre a estrutura e o significado dos nossos dados.

Foram adicionadas as classes:
- Legível
- Consumível
- Parte
- Genital
- Cabeça
- Olho

**Alterações Realizadas:**

- Incluí informações detalhadas sobre os atributos, tipos de dados, tamanhos e restrições de domínio relacionados a essa parte específica do diagrama.
- Garanti que a documentação esteja completa e siga as melhores práticas de documentação de dados.

**Motivação:**

A documentação do dicionário de dados é essencial para garantir que todos os membros da equipe tenham uma compreensão clara da estrutura e dos requisitos dos nossos dados. Isso facilita o desenvolvimento, a manutenção e a colaboração em nosso projeto.

**Testes Realizados:**

Verifiquei cuidadosamente a precisão e a integridade das informações fornecidas no dicionário de dados.

**Revisão:**

Peço a revisão e o feedback dos colegas da equipe para garantir que o dicionário de dados esteja completo e preciso.

**Próximos Passos:**

Após a revisão e a aprovação, continuarei a adicionar mais partes do diagrama ao nosso dicionário de dados para abranger todas as entidades e relacionamentos relevantes.

Agradeço a todos pela colaboração e pela atenção a este importante aspecto da documentação do projeto.

2023-09-26 21:56 UTC, PedroLimass approved these changes
Ta show!

2023-10-01 20:54 UTC, gatotabaco requested changes

2023-10-01 20:54 UTC, gatotabaco commented on docs/modulo_01/dicionarioDeDados.md
> +| **Descrição**   | Personagem jogável |     |     |     |     |
Descrição errada! Não é a tabela do personagem jogável

2023-10-01 20:54 UTC, gatotabaco commented on docs/modulo_01/dicionarioDeDados.md
> +| Vida       | hp        | vida da parte                  | int          | 4       | Default               |
Já tem o atributo de vida máxima em "parte". Está repetido.

Isso serve para todas as partes que vc tbm colocou o atributo hp

2023-10-02 20:01 UTC, heylisten64 commented
fora as correcoes ja listadas, tudo ok!

2023-10-02 20:03 UTC, heylisten64 approved these changes
fora as correcoes ja listadas, tudo ok!

2023-10-03 01:27 UTC, merged